Update index and update lk kapalcumi
landx-id/landx_landing pull request #119
Opened 2021-08-23 08:21 UTC by almibiakmal

1. Penambahan card pada file index
2. Penambahan upcoming json di folder lottie
3. Update referensi data file lp/kapalcumi/script/detailUpcoming.js

2021-08-23 09:52 UTC, glendmaatita requested changes

2021-08-23 09:52 UTC, glendmaatita commented on index.html
> +    <link rel="stylesheet" href="lp/kapalcumi/card.css">
@almibiakmal  if it used in index.html from the root project folder, it should be global stylesheet, not project specific

2021-08-23 09:52 UTC, glendmaatita commented on index.html
> +    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
@almibiakmal plase make sure it doesn't drag any problem on another pages

2021-08-23 09:52 UTC, glendmaatita commented on lottie/upcoming.json
> +                "images": "lp/kapalcumi/assets/2.png",
@almibiakmal  make images as array. we'll never know how many images we need per project

2021-08-23 10:00 UTC, almibiakmal commented on lottie/upcoming.json
> +                "images": "lp/kapalcumi/assets/2.png",
Are you sure?
Because, based on allan's design I'm using it only as a thumbnail, so it looks like there's only 1 image for the upcoming project.

2021-08-23 10:01 UTC, almibiakmal commented on lottie/upcoming.json
> +                "images": "lp/kapalcumi/assets/2.png",
But, if it's really needed I can update it

2021-08-24 02:29 UTC, glendmaatita commented on lottie/upcoming.json
> +                "images": "lp/kapalcumi/assets/2.png",
yes @almibiakmal . make it as array

2021-08-25 06:43 UTC, closed without merging